### ISSUE TITLE
Can't auto fix decorators correctly

### ISSUE THREAD

**Issue by jk195417** [rdlabo-team/eslint-plugin-rules#2]
First of all, thank you for developing this great lib, it save times on migrate to inject fn instead of inject in consturctor.

There is a little glitch, can't auto fix decorators correctly, for example, inject a injection token in consturctor with decorator @Inject, will get wrong result.

**Comment by rdlabo** [comment]
Thanks for the Issue. We are aware that some automated fixes do not work, but since most projects are rarely massive, please fix them manually.
