### ISSUE TITLE
Auto-fix deny-constructor-di lost with access modifiers

### ISSUE THREAD

**Issue by XavierDupessey** [rdlabo-team/eslint-plugin-rules#4]
Hello,

I tried to apply the auto-fix `@rdlabo/rules/deny-constructor-di` and apparently it struggles with access modifiers.
In some cases, it defines a property `public private`.

The source code:
```typescript
@Injectable()
export class AuthComponentService {
  public constructor(private http: HttpClient, private router: Router, private config: AuthConfigService) {}
  
  [...]
}
```

Is converted to:
```typescript
@Injectable()
export class AuthComponentService {
  public private http = inject(HttpClient);
         private router = inject(Router);
         private config = inject(AuthConfigService);
         
         constructor() {}
  [...]
}
```

**Comment by rdlabo** [comment]
`public constructor` is not supported.

**Comment by XavierDupessey** [comment]
Out of curiosity, why don't you want to support it? Only because "public" is the default access modifier? cf https://www.typescriptlang.org/docs/handbook/classes.html#public-by-default

It would exclude people from using your auto-fix but of course this is your choice :)
